name: Enhancement or Feature
description: Use this with related PR that you created
title: "<title>"
labels: enhancement
body:
- type: markdown
  attributes:
    value: "### Thank you for contributing to this project!"
- type: textarea
  attributes:
    label: Is this enhancement or feature is related to a problem?
    description: | 
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the solution you'd like
    placeholder: A clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe alternatives you've considered
    placeholder: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context
    placeholder: Add any other context or screenshots about the feature request here.
  validations:
    required: false
